version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: raft-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - raft-network

  # Raft节点1
  raft-node-1:
    build:
      context: ./distribute-java-core
      dockerfile: Dockerfile
    container_name: raft-node-1
    ports:
      - "8051:8051"
    environment:
      - RAFT_NODE_ID=1
      - RAFT_NODE_PORT=8051
      - RAFT_CLUSTER_NODES=raft-node-1:8051,raft-node-2:8052,raft-node-3:8053
      - RAFT_DATA_PATH=/app/data
    volumes:
      - raft_node_1_data:/app/data
      - raft_node_1_logs:/app/logs
    depends_on:
      - redis
    networks:
      - raft-network
    restart: unless-stopped

  # Raft节点2
  raft-node-2:
    build:
      context: ./distribute-java-core
      dockerfile: Dockerfile
    container_name: raft-node-2
    ports:
      - "8052:8052"
    environment:
      - RAFT_NODE_ID=2
      - RAFT_NODE_PORT=8052
      - RAFT_CLUSTER_NODES=raft-node-1:8051,raft-node-2:8052,raft-node-3:8053
      - RAFT_DATA_PATH=/app/data
    volumes:
      - raft_node_2_data:/app/data
      - raft_node_2_logs:/app/logs
    depends_on:
      - redis
    networks:
      - raft-network
    restart: unless-stopped

  # Raft节点3
  raft-node-3:
    build:
      context: ./distribute-java-core
      dockerfile: Dockerfile
    container_name: raft-node-3
    ports:
      - "8053:8053"
    environment:
      - RAFT_NODE_ID=3
      - RAFT_NODE_PORT=8053
      - RAFT_CLUSTER_NODES=raft-node-1:8051,raft-node-2:8052,raft-node-3:8053
      - RAFT_DATA_PATH=/app/data
    volumes:
      - raft_node_3_data:/app/data
      - raft_node_3_logs:/app/logs
    depends_on:
      - redis
    networks:
      - raft-network
    restart: unless-stopped

  # Spring Boot API服务
  api-server:
    build:
      context: ./spring-boot-api
      dockerfile: Dockerfile
    container_name: raft-api-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RAFT_CLUSTER_NODES=raft-node-1:8051,raft-node-2:8052,raft-node-3:8053
    volumes:
      - api_logs:/app/logs
    depends_on:
      - redis
      - raft-node-1
      - raft-node-2
      - raft-node-3
    networks:
      - raft-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/monitoring/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus监控
  prometheus:
    image: prom/prometheus:latest
    container_name: raft-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - raft-network
    restart: unless-stopped

  # Grafana监控面板
  grafana:
    image: grafana/grafana:latest
    container_name: raft-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - raft-network
    restart: unless-stopped

volumes:
  redis_data:
  raft_node_1_data:
  raft_node_1_logs:
  raft_node_2_data:
  raft_node_2_logs:
  raft_node_3_data:
  raft_node_3_logs:
  api_logs:
  prometheus_data:
  grafana_data:

networks:
  raft-network:
    driver: bridge
