version: '3.8'

services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --replica-announce-ip redis-master
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network
    restart: unless-stopped

  # Redis Slave 1
  redis-slave-1:
    image: redis:7-alpine
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --replicaof redis-master 6379 --replica-announce-ip redis-slave-1
    volumes:
      - redis-slave-1-data:/data
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped

  # Redis Slave 2
  redis-slave-2:
    image: redis:7-alpine
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes --replicaof redis-master 6379 --replica-announce-ip redis-slave-2
    volumes:
      - redis-slave-2-data:/data
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: unless-stopped

volumes:
  redis-master-data:
  redis-slave-1-data:
  redis-slave-2-data:

networks:
  redis-network:
    driver: bridge 